apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Hello Word</title>
      <style>
        body { font-family: sans-serif; text-align: center; margin-top: 50px; }
        h1 { color: #2e7d32; }
      </style>
    </head>
    <body>
      <h1> It works!</h1>
    </body>
    </html>