{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name | default (printf "%s-index" (include "temaotl-nginx-unprivileged.fullname" .)) }}
  labels:
    {{- include "temaotl-nginx-unprivileged.labels" . | nindent 4 }}
data:
{{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
