{{- if .Values.persistence.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName | default (printf "%s-pvc" (include "temaotl-nginx-unprivileged.fullname" .)) }}
  labels:
    {{- include "temaotl-nginx-unprivileged.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
