apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: testapp-route
  namespace: default    
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`testapp.localhost`) && PathPrefix(`/`) && !PathPrefix(`/api`)
      kind: Rule
      services:
        - name: testapp-front-svc
          kind: Service
          port: 80